# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af021c448f37f12d2f5c55a105e9d243f839d28cfede12ea6f236717b3c602a7052f1ea73fa53593b01471a6340d30969dfd8b65def0fd6c06a0552e00281151

test:
  secret_key_base: 3cac8765343aa97d95a973adbaa710ccf887d8e119643ea1b40bc859ae600590ee27ff59a6347cca3002b45d5d098416435d1b6da4c330908639bfb40894652a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
